### ISSUE TITLE
Dynamic routing error

### ISSUE THREAD

**Issue by mrjasonjiang** [ziping-li/convue#1]
dynamic routing错误
编译后：convue/dist/index.js 文件
const allPaths = routes.map(n => n.path);
应该为：
const allPaths = routes[0].children.map(n => n.path);

对应源码文件：convue/src/pages/generate.ts
const allPaths = routes.map(n => n.path);
应该为：
const allPaths = routes[0].children.map(n => n.path);
不知道是不是这里，反正，我修改了这里，动态路由就没问题了

**Comment by ziping-li** [comment]
已修复，对应版本为1.0.5，谢谢。
