### ISSUE TITLE
动态路由问题

### ISSUE THREAD

**Issue by mrjasonjiang** [ziping-li/convue#2]
接上个issue，
**一、**
您，package.json中
指向的dist/index.js文件，在发布npm时没有重新编译,在tsx没问题，sfc是有问题的
😂
**二、**
还有就是，在tsx下，动态路由扫描是否有问题，pages目录有文件
-- 404.tsx
-- about.tsx
-- index.tsx
扫描之后的内容为
[
  {
    "path": "/404",
    "component": _src_pages_404_tsx,
    },
    "children": [
      {
        "name": "about",
        "path": "",
        "component": _src_pages_about_tsx,
        "props": true
      }
    ],
    "props": true,
    "name": "404"
  },
  {
    "name": "index",
    "path": "/",
    "component": _src_pages_index_tsx,
    },
    "props": true
  }
]
about路由在404下

**Comment by mrjasonjiang** [comment]
get，在tsx下，route标签内必须添加path，且必须有/前缀
about.tsx
{/* <route>
  name: 'about'
  path: '/about'
 -----
</route> */}

**Comment by ziping-li** [comment]
本来打算这几天规范化的，没想到就有人用了，今晚回去帮您看这个问题:-P



---原始邮件---
发件人: "mrjasonjiang"<notifications@github.com&gt;
发送时间: 2021年2月23日(周二) 下午3:20
收件人: "ziping-li/convue"<convue@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [ziping-li/convue] 动态路由问题 (#2)




 
get，在tsx下，route标签内必须添加path，且必须有/前缀
 about.tsx
 {/* 
 name: 'about'
 path: '/about'
 
 */}

**Comment by ziping-li** [comment]
fixed on 1.0.6
