### ISSUE TITLE
能否支持npm?

### ISSUE THREAD

**Issue by rainmanhhh** [ziping-li/convue#6]
现在默认强制是yarn，可以支持npm吗

**Comment by ziping-li** [comment]
都支持的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月16日(周二) 中午11:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ziping-li/convue] 能否支持npm? (#6)




 
现在默认强制是yarn，可以支持npm吗

**Comment by rainmanhhh** [comment]
哦，不过执行convue选完模式之后它会自动用yarn install，这个可以跳过吗

**Comment by ziping-li** [comment]
在安装那一步取消，进入项目手动执行npm安装也可以------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月17日(星期三) 晚上6:38
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [ziping-li/convue] 能否支持npm? (#6)
